export const teams = [
	{ id: 1, value: "Cardinals", name: "Arizona Cardinals" },
	{ id: 2, value: "Falcons", name: "Atlanta Falcons" },
	{ id: 3, value: "Ravens", name: "Baltimore Ravens" },
	{ id: 4, value: "Bills", name: "Buffalo Bills" },
	{ id: 5, value: "Panthers", name: "Carolina Panthers" },
	{ id: 6, value: "Bears", name: "Chicago Bears" },
	{ id: 7, value: "Bengals", name: "Cincinnati Bengals" },
	{ id: 8, value: "Browns", name: "Cleveland Browns" },
	{ id: 9, value: "Cowboys", name: "Dallas Cowboys" },
	{ id: 10, value: "Broncos", name: "Denver Broncos" },
	{ id: 11, value: "Lions", name: "Detroit Lions" },
	{ id: 12, value: "Packers", name: "Green Bay Packers" },
	{ id: 13, value: "Texans", name: "Houston Texans" },
	{ id: 14, value: "Colts", name: "Indianapolis Colts" },
	{ id: 15, value: "Jaguars", name: "Jacksonville Jaguars" },
	{ id: 16, value: "Chiefs", name: "Kansas City Chiefs" },
	{ id: 17, value: "Raiders", name: "Las Vegas Raiders" },
	{ id: 18, value: "Chargers", name: "Los Angeles Chargers" },
	{ id: 19, value: "Rams", name: "Los Angeles Rams" },
	{ id: 20, value: "Dolphins", name: "Miami Dolphins" },
	{ id: 21, value: "Vikings", name: "Minnesota Vikings" },
	{ id: 22, value: "Patriots", name: "New England Patriots" },
	{ id: 23, value: "Saints", name: "New Orleans Saints" },
	{ id: 24, value: "Giants", name: "New York Giants" },
	{ id: 25, value: "Jets", name: "New York Jets" },
	{ id: 26, value: "Eagles", name: "Philadelphia Eagles" },
	{ id: 27, value: "Steelers", name: "Pittsburgh Steelers" },
	{ id: 28, value: "49ers", name: "San Francisco 49ers" },
	{ id: 29, value: "Seahawks", name: "Seattle Seahawks" },
	{ id: 30, value: "Buccaneers", name: "Tampa Bay Buccaneers" },
	{ id: 31, value: "Titans", name: "Tennessee Titans" },
	{ id: 32, value: "Commanders", name: "Washington Commanders" },
];
